name: Create Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
         github-token: ${{ secrets.PERSONAL_TOKEN }}
         script: |
            github.rest.actions.createWorkflowDispatch({
              owner: Significant-Gravitas,
              repo: Auto-GPT,
              workflow_id: 'test.yml',
              ref: 'main',
            })
